### ISSUE TITLE
SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by kevinthr** [ide/dash-button#7]
When I try to do 'sudo npm run scan' I get this error. If I just try to remove 'use strict' from that file, it breaks it in another way. How can I make this work? I'm on OS X. I tried updating node. Here's the error:

`/Users/kevinthr/Dropbox/Work/n04 dash/node_modules/dash-button/build/cli.js:29`
`  let parser = _yargs2.default.usage('Usage: $0 <command> [options]').command(`
`  ^^^`
`SyntaxError: Unexpected strict mode reserved word`
`    at Module._compile (module.js:439:25)`
`    at Object.Module._extensions..js (module.js:474:10)`
`    at Module.load (module.js:356:32)`
`    at Function.Module._load (module.js:312:12)`
`    at Function.Module.runMain (module.js:497:10)`
`    at startup (node.js:119:16)`
`    at node.js:906:3`

**Comment by KishPatel1996** [comment]
Running into the same error when importing DashButton.  How did you solve it?
